language: bash
services: docker
addons:
  apt:
    packages:
    - qemu-user-static
before_install:
- sudo update-binfmts --enable qemu-${ARCH}
before_script:
- wget -nv http://os.archlinuxarm.org/os/ArchLinuxARM-${CARCH}-latest.tar.gz
- wget -nv http://os.archlinuxarm.org/os/ArchLinuxARM-${CARCH}-latest.tar.gz.md5
- wget -nv http://os.archlinuxarm.org/os/ArchLinuxARM-${CARCH}-latest.tar.gz.sig
- md5sum -c ArchLinuxARM-${CARCH}-latest.tar.gz.md5
- gpg --recv-keys 68B3537F39A313B3E574D06777193F152BDBE6A6
- gpg --verify ArchLinuxARM-${CARCH}-latest.tar.gz.sig ArchLinuxARM-${CARCH}-latest.tar.gz
- wget -nv https://github.com/multiarch/qemu-user-static/releases/download/v3.1.0-3/qemu-${ARCH}-static
  -O qemu-${ARCH}-static
- chmod +x qemu-${ARCH}-static
- sed -e "s|%ARCH%|${ARCH}|g" -e "s|%CARCH%|${CARCH}|g" -i 'Dockerfile'
- echo '{"experimental":true}' | sudo tee /etc/docker/daemon.json
- sudo service docker restart
script:
- docker build --squash -t mydatakeeper/archlinuxarm:${TAG} .
deploy:
  provider: script
  script: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    && docker push mydatakeeper/archlinuxarm:${TAG}
  on:
    branch: master
matrix:
  include:
  - env:
    - ARCH=arm
    - CARCH=armv5
    - TAG=arm
  - env:
    - ARCH=arm
    - CARCH=rpi
    - TAG=armv6h
  - env:
    - ARCH=arm
    - CARCH=armv7
    - TAG=armv7h
  - env:
    - ARCH=aarch64
    - CARCH=aarch64
    - TAG=aarch64
env:
  global:
  - secure: pWOYZWl1Xv73CeQ4h1zFx/0gchFoWwJtXtrZbxHnpe+p0YyuHIbvQDLxjk7yK4SC1nghp0LVEECTkzZwS/vQTW1/zLXkWJQfhgwZEPDPEk8XgvFn5oK50/AcZqG7PPAHReXcXkPgvMjOaLzYL6fG0NAEmw8sQBTXucrHuNssgxv0r9JU1Ur+DZGZZ4N06I6JYgbilqfeE/GrOd+2buO2FPtPgnOugI6ApXIKK5KFk4h4ZiMSHmVFUUc3RGXxJzsWXiqbzjZswUKN8CkOZ8zG6xD4t+xHWFsZwvuuYKwp2H+7iUDlopl1ouFHg+PO1j+lgeytqplI1ybK0emjEUyTg1RLCRu0Sx/rZjW3tmGkovpNrkHuZu/Ad0Zgqr5bJwrB9IsulAfssINtRQIptFhAIgPJ5MPrUAA398Fi16JZrPgdh6NP4DZBCaHvn1trAiYX3fMBV8mlTtJQskIYNC8MbQQa+D62aq1G42FZqFfqUWvX61/M662nomFqVmvmTcmItph5lanyECNvkI6G5T1rEWjX0Qgj+S7P6vKigKYk4QFVqL24+497j8ufKamf8KOO0SsfY4dLbUrfKg2HV7i9E1L3fWWROCzliuIMb6z2KWtOQEu6GkwcXK1ULwDWTLbKMpT3IT43FoNh97SXvJJ5KKjTbsCV6rNdM7VXIuegnvA=
  - secure: JSwTreNn6UsPhko781BeljKUc/pQOJc6jz18tNGvSuy+qSZg27sNsSJlVIygB5TN1APJnPu20WdKuT4yQY/c64jcd4AHIJETa8CIdJrF6qb9X9a7wfdVmUQ6TkPqHsV/xDwjoL4UjwlKxAnWQGmwGTRThFTwR2dpeNNNN/cmrTZWgJ9kua3VPLhAJrgDhoCizKMujnldRb+2OMdPPr4H7rxlCg1I1m55A/7pl2PWjcBD7saXq78hy9k4NF4YjNuYm/wGARZPqA+fIBH0iMcJthWhIB9KA/z3pWD+b6QWGP0cEMWOLSutQF/7mySgbR44mJuHiSWrQ5sbl009wOSilK9e+zbILVFHMDsCDGuMJPIaBCBArncb7ugSyFQEkPrq5snZy9kOPiGl2r9AbxQWyoDxm7Nysbqg94+HwT00SMNkPC0Jkam7zd0NoUIzYbBHT25BVajlSUGe0+8kRpNq4N9h26Dyxp5cJtEuZG1ZvqpHc1PNHtJC31cu4TUNXH8IyHM653KGv6wVmTLmiiNPrWuuSTnD/IWftS78vx3ceSLGATJ758U+75hgICDy5yCUPRzLOJZRLyW48lR+IuA0/byHI4eg1J8qW08WFducwsCozh0jiarCYQ8ke3lBEaQ/IGHdRlqdlzQ7do5KrK8dQPzaRMNM2kwd6xH6DYb64gc=
