language: bash
services: docker

addons:
  apt:
    packages:
    - qemu-user-static

before_install:
  - sudo update-binfmts --enable qemu-${ARCH}

before_script:
  - wget -nv http://os.archlinuxarm.org/os/ArchLinuxARM-${CARCH}-latest.tar.gz
  - wget -nv http://os.archlinuxarm.org/os/ArchLinuxARM-${CARCH}-latest.tar.gz.md5
  - wget -nv http://os.archlinuxarm.org/os/ArchLinuxARM-${CARCH}-latest.tar.gz.sig
  - md5sum -c ArchLinuxARM-${CARCH}-latest.tar.gz.md5
  - gpg --recv-keys 68B3537F39A313B3E574D06777193F152BDBE6A6
  - gpg --verify ArchLinuxARM-${CARCH}-latest.tar.gz.sig ArchLinuxARM-${CARCH}-latest.tar.gz
  - wget -nv https://github.com/multiarch/qemu-user-static/releases/download/v3.1.0-3/qemu-${ARCH}-static -O qemu-${ARCH}-static
  - chmod +x qemu-${ARCH}-static

script:
  - docker build -t mydatakeeper/archlinuxarm:${CARCH} .

deploy:
  provider: script
  script: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin && docker push mydatakeeper/archlinuxarm:${CARCH}
  on:
    branch: master

matrix:
  include:
    - env:
      - CARCH=aarch64
      - ARCH=aarch64
#    - env:
#      - CARCH=armv7
#      - ARCH=arm
