language: bash
services: docker
addons:
  apt:
    packages:
    - qemu-user-static
before_install:
- sudo update-binfmts --enable qemu-${ARCH}
before_script:
- wget -nv http://os.archlinuxarm.org/os/ArchLinuxARM-${CARCH}-latest.tar.gz
- wget -nv http://os.archlinuxarm.org/os/ArchLinuxARM-${CARCH}-latest.tar.gz.md5
- wget -nv http://os.archlinuxarm.org/os/ArchLinuxARM-${CARCH}-latest.tar.gz.sig
- md5sum -c ArchLinuxARM-${CARCH}-latest.tar.gz.md5
- gpg --recv-keys 68B3537F39A313B3E574D06777193F152BDBE6A6
- gpg --verify ArchLinuxARM-${CARCH}-latest.tar.gz.sig ArchLinuxARM-${CARCH}-latest.tar.gz
- wget -nv https://github.com/multiarch/qemu-user-static/releases/download/v3.1.0-3/qemu-${ARCH}-static
  -O qemu-${ARCH}-static
- chmod +x qemu-${ARCH}-static
- sed -e "s|%ARCH%|${ARCH}|g" -e "s|%CARCH%|${CARCH}|g" -i 'Dockerfile'
script:
- docker build -t mydatakeeper/archlinuxarm:${CARCH} .
deploy:
  provider: script
  script: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    && docker push mydatakeeper/archlinuxarm:${CARCH}
  on:
    branch: master
matrix:
  include:
  - env:
    - ARCH=arm
    - CARCH=arietta
  - env:
    - ARCH=arm
    - CARCH=kirkwood
  - env:
    - ARCH=arm
    - CARCH=armv5
  - env:
    - ARCH=arm
    - CARCH=mmp
  - env:
    - ARCH=arm
    - CARCH=rpi
  - env:
    - ARCH=arm
    - CARCH=am33x
  - env:
    - ARCH=arm
    - CARCH=mirabox
  - env:
    - ARCH=arm
    - CARCH=smileplug
  - env:
    - ARCH=arm
    - CARCH=d3plug
  - env:
    - ARCH=arm
    - CARCH=odroid-x
  - env:
    - ARCH=arm
    - CARCH=odroid
  - env:
    - ARCH=arm
    - CARCH=odroid-xu
  - env:
    - ARCH=arm
    - CARCH=usbarmory
  - env:
    - ARCH=arm
    - CARCH=armv7
  - env:
    - ARCH=arm
    - CARCH=armv7-chromebook
  - env:
    - ARCH=arm
    - CARCH=rpi-2
  - env:
    - ARCH=aarch64
    - CARCH=aarch64
  - env:
    - ARCH=aarch64
    - CARCH=aarch64-chromebook
  - env:
    - ARCH=aarch64
    - CARCH=odroid-c2
  - env:
    - ARCH=aarch64
    - CARCH=odroid-n2
  - env:
    - ARCH=aarch64
    - CARCH=oak
  - env:
    - ARCH=aarch64
    - CARCH=dragonboard410c
  - env:
    - ARCH=aarch64
    - CARCH=rpi-3
  - env:
    - ARCH=aarch64
    - CARCH=gru
env:
  global:
  - secure: gQleBBN1l1c9xzlkRrl/4cFgi3v3vJ+HZsJmo+sBu7yCjBYr9qgsyBd33aXdHp+ngIf48DQng/p6iVoNa00dOHh2UCuiU09/qy37xv/HLgO3NsQM7RGgKMqKMsOruthvaDxnaQ20y6nr3dNG0ZbHsBsDs8gNNiUK0i1U6QVD9V9xLlZaU757tH/h+Kh74/tPU10I0OL5nykdzdkblazL1b3X3Ewunolj+rj5TJRF1Nfp2Y9u421foQgZz8rqJZmB0Xnwp1zlJgwK4C6TPE61JbVJL0aKcVcK8M57os73RuylAVRg+8CW9kaWu5NRxZ+YKUfOCOxAPVDF4wj16cw+qyJ+ogMJ2T6Q+Dv0zMTGvUKxaCB2xXn9K8s+LesBKEtZ6r91ROYng4ENyfiA+n0jDSIVjL605EIv2nR7vQEsdjOuWptfU4/LkKsdYAOkUKh2GL8BU78IbHp4cScjM4GY+OZNSX9ViwlkMKXbp3KGZ45rGMMhuVGziXdbFe1mC0/NLDw5Q+mUE2Q0RNzxNyjDnU2vQ/3Dg3/rA5y9zBw4p8Yrhy7Mk29xREYRB7vwHv1JY7js1hboWDDSAoSVrhXM65AcTRc34bm6c44SNAHF9M7LdUES6hRNJkIzBym+TYZov+70z/wpZfblfZR9miJCefkf8+dfzsJsLcDLjXav+sE=
  - secure: VL7XIITuGa+58R0qzpm20QAe/H2Op4D7JBeAW24qTX4D1VHFgBXLIPtFcuxLM7TLO29uogXwLW0rmic8Hv+34p9/yDPGOIzwj+d6dy2dEid4ViugbFuWSVHjMEwBGUcgaMBBYCxrT7mtkM9fJVGUnFCSuM71B4xnChML/h8/35rV8GmkC4w2ufpeP9Z7BbEGRizrmbAJJTA0A8sSBquvZ3bGC8fs6WnD4sEL1v8c1pSZJTxhVhmOQO5tlf40W/+22dQAhqIaqhTPLJY+mY1ySETM8GA9b+ZrGKKap3XuHdz2aER90qmB2oC9QKmRfT6Cp8cVl4QpOQ/lbo1/G57fjIw4kxByFAp79U2RCAHBvsQQJ8Dy+HyQZOFlCh73Yl8cgxxygoLdUPc8bG7+MbxUm/BwXGYbcbYKht8CDOcJyJbol8OkvBwre45oojuRvi6zcrJ05Jb4dXfbu2uh2nbEmkUtSeaPC9abojsTlOKx2unlRK3PvtdUg10JReqb9RWXn8nuhXROMoquUES6HHffE7Wmw3Syyq8MozNPUxi0HQ2QS79DBXd3nTNcw9YpIQBp4DxMf3N5b0EEps+8HGmqT7LP5xBIvn1VAFX3A/yhZbysOHkuDmniyUlEzpfQ1+M/y9/+f+U0up7KU0T3dHMjb3fCnuPV02eU7yFwNGKn45Y=
