language: bash
services: docker
addons:
  apt:
    packages:
    - qemu-user-static
before_install:
- sudo update-binfmts --enable qemu-${ARCH}
before_script:
- wget -nv http://os.archlinuxarm.org/os/ArchLinuxARM-${CARCH}-latest.tar.gz
- wget -nv http://os.archlinuxarm.org/os/ArchLinuxARM-${CARCH}-latest.tar.gz.md5
- wget -nv http://os.archlinuxarm.org/os/ArchLinuxARM-${CARCH}-latest.tar.gz.sig
- md5sum -c ArchLinuxARM-${CARCH}-latest.tar.gz.md5
- gpg --recv-keys 68B3537F39A313B3E574D06777193F152BDBE6A6
- gpg --verify ArchLinuxARM-${CARCH}-latest.tar.gz.sig ArchLinuxARM-${CARCH}-latest.tar.gz
- wget -nv https://github.com/multiarch/qemu-user-static/releases/download/v3.1.0-3/qemu-${ARCH}-static
  -O qemu-${ARCH}-static
- chmod +x qemu-${ARCH}-static
- sed -e "s|%ARCH%|${ARCH}|g" -e "s|%CARCH%|${CARCH}|g" -i 'Dockerfile'
script:
- docker build -t mydatakeeper/archlinuxarm:${CARCH} .
deploy:
  provider: script
  script: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    && docker push mydatakeeper/archlinuxarm:${CARCH}
  on:
    branch: master
matrix:
  include:
  - env:
    - ARCH=arm
    - CARCH=arietta
  - env:
    - ARCH=arm
    - CARCH=kirkwood
  - env:
    - ARCH=arm
    - CARCH=armv5
  - env:
    - ARCH=arm
    - CARCH=mmp
  - env:
    - ARCH=arm
    - CARCH=rpi
  - env:
    - ARCH=arm
    - CARCH=am33x
  - env:
    - ARCH=arm
    - CARCH=mirabox
  - env:
    - ARCH=arm
    - CARCH=smileplug
  - env:
    - ARCH=arm
    - CARCH=d3plug
  - env:
    - ARCH=arm
    - CARCH=odroid-x
  - env:
    - ARCH=arm
    - CARCH=odroid
  - env:
    - ARCH=arm
    - CARCH=odroid-xu
  - env:
    - ARCH=arm
    - CARCH=usbarmory
  - env:
    - ARCH=arm
    - CARCH=armv7
  - env:
    - ARCH=arm
    - CARCH=armv7-chromebook
  - env:
    - ARCH=arm
    - CARCH=rpi-2
  - env:
    - ARCH=aarch64
    - CARCH=aarch64
  - env:
    - ARCH=aarch64
    - CARCH=aarch64-chromebook
  - env:
    - ARCH=aarch64
    - CARCH=odroid-c2
  - env:
    - ARCH=aarch64
    - CARCH=odroid-n2
  - env:
    - ARCH=aarch64
    - CARCH=oak
  - env:
    - ARCH=aarch64
    - CARCH=dragonboard410c
  - env:
    - ARCH=aarch64
    - CARCH=rpi-3
  - env:
    - ARCH=aarch64
    - CARCH=gru
env:
  global:
  - secure: JX3BDRu4OKhaRNvCuWeE7fvi7W6AFS+Z62HTFOaw7fU0gYJ9LBgSLPnAWm58yEe//ucUEzQFJIncEAgm95x7QiluGRVA6SjmaSGX5WPDgbzDsyCF4IYPDubRVmHFB9VJiQ1wrE2H0N3PeJ27mRYQ0lD9e83hTB2ayVT0P4chV3BuHaX/bmoyU6AuT31BzIfTgyeYh333aNhgcUzlok5Q4hvAGMHYTOpccju7rKpDrGO/F49VW/H3pS/oSNjDb3Y+HEb+rY95cS3e9wFynzC5BNh1lTPYKAZ8vo07H3DlAg39YgFE5pwyJiaXggB+1bgBJshPS5XafT22iUfnsnAKkUDIGD8l1yMaZ98c1rY6l4OJbVI65elC1ngb7P7Gr3L3hzsBfox5n1LOcFT7+u3pMQYgggYtDQSRmZBNnRc0xT9r6ZpUrle6vEevzGVnFEp9TQPAreDAjhasAwuC12u14s4UCE1uWCAe1vJW2tMnICQFSSEFIgfQM+f0nyIvHuasJuDLhjQJK+qQaMC18j19+6ciIT/1nYEepntFIw5Pxoog5ka1uyiYQf9mr/EJKNIwoNeLdWjMk5Y50um2CKCjSFDmhIbQTxiSpcxQBzC+kOeT0lSlQdi6X5+UsuMzooAbwdEE30M95AH4JrswJ5beN4iteHpSe3EblvUGtMje+Wg=
  - secure: qmna0+Y6U9Qy+LlbiOaPtKbIJvoGKKXn/dbiy5VcB8DPxkhNdMd3S22saL0pCNmCD1phnkSAZu0fuU3Q3/ASVpc2px9k0LCT1Sl9YISNXoTO/Ht8MGJGIHBfuiyIQJ1X5oa8GAf3f4a46nryaJCI8vM+96oyTVKiGhDxNrCasw16AioGTcY1SrclQSIPcANHBzgABED8fKumlh7bkCh+wHz1y/mRW3v9dUeAxDebZdCx3N6Wr1toTwt0Y8NYdrC9UknsjlZmuD7yGmQY8ohKKzJqW5rapP65FUsmAker9XHZ8VhxfbBC1UN7K63v5Xmj6a/DTRKhiJYWGebELfM9vZG1mhkHdhQz8+kq9CvOvRtZDHHiLHJgiEcvgd1D2N/X0XwrqLCwwp5HCJetN62oiyccjHd4z5+5Y8kAsxFJTWoZedF1m+L5AcOlT/KO9SlFAIO8g+ubskh3Y32FAssm9sGxY9q9ri62VNcv/5ChhbfIOwz1NGeTEkNJnwYmDJtyfbIfNcbO7DA7Dk2UAapjAoA+bmuhVqckn7wgkc66iBf5thvIzm7FIUe5PEDgYoB06bJylFsSbtB0aODMFuRp/XgYC276yvMG+YfRm/2XZHJPe4uhkjXlIapse0tEiM+5zNhsydSs56zLEXZxAC2KQGAuiSUGCutCWsCeYPVgbxA=
