language: bash
services: docker

addons:
  apt:
    packages:
    - qemu-user-static

before_install:
  - sudo update-binfmts --enable qemu-${ARCH}

before_script:
  - wget -nv http://os.archlinuxarm.org/os/ArchLinuxARM-${CARCH}-latest.tar.gz
  - wget -nv http://os.archlinuxarm.org/os/ArchLinuxARM-${CARCH}-latest.tar.gz.md5
  - wget -nv http://os.archlinuxarm.org/os/ArchLinuxARM-${CARCH}-latest.tar.gz.sig
  - md5sum -c ArchLinuxARM-${CARCH}-latest.tar.gz.md5
  - gpg --recv-keys 68B3537F39A313B3E574D06777193F152BDBE6A6
  - gpg --verify ArchLinuxARM-${CARCH}-latest.tar.gz.sig ArchLinuxARM-${CARCH}-latest.tar.gz
  - wget -nv https://github.com/multiarch/qemu-user-static/releases/download/v3.1.0-3/qemu-${ARCH}-static -O qemu-${ARCH}-static
  - chmod +x qemu-${ARCH}-static
  - sed -e "s|%ARCH%|${ARCH}|g" -e "s|%CARCH%|${CARCH}|g" -i 'Dockerfile'


script:
  - docker build -t mydatakeeper/archlinuxarm:${CARCH} .

deploy:
  provider: script
  script: echo "$DOCKER_PASSPHRASE" | docker login -u "$DOCKER_USER" --password-stdin && docker push mydatakeeper/archlinuxarm:${CARCH}
  on:
    branch: master

matrix:
  include:
    - env:
      - ARCH=arm
      - CARCH=arietta
    - env:
      - ARCH=arm
      - CARCH=kirkwood
    - env:
      - ARCH=arm
      - CARCH=armv5
    - env:
      - ARCH=arm
      - CARCH=mmp
    - env:
      - ARCH=arm
      - CARCH=rpi
    - env:
      - ARCH=arm
      - CARCH=am33x
    # - env:
    #   - ARCH=arm
    #   - CARCH=odroid-c1
    - env:
      - ARCH=arm
      - CARCH=mirabox
    - env:
      - ARCH=arm
      - CARCH=smileplug
    # - env:
    #   - ARCH=arm
    #   - CARCH=cubox
    - env:
      - ARCH=arm
      - CARCH=d3plug
    - env:
      - ARCH=arm
      - CARCH=odroid-x
    - env:
      - ARCH=arm
      - CARCH=odroid
    - env:
      - ARCH=arm
      - CARCH=odroid-xu
    # - env:
    #   - ARCH=arm
    #   - CARCH=odroid-xu3
    - env:
      - ARCH=arm
      - CARCH=usbarmory
    # - env:
    #   - ARCH=arm
    #   - CARCH=imx6-cubox
    # - env:
    #   - ARCH=arm
    #   - CARCH=utilite
    - env:
      - ARCH=arm
      - CARCH=armv7
    - env:
      - ARCH=arm
      - CARCH=armv7-chromebook
    - env:
      - ARCH=arm
      - CARCH=rpi-2
    # - env:
    #   - ARCH=arm
    #   - CARCH=veyron
    # - env:
    #   - ARCH=arm
    #   - CARCH=zedboard
    - env:
      - ARCH=aarch64
      - CARCH=aarch64
    - env:
      - ARCH=aarch64
      - CARCH=aarch64-chromebook
    - env:
      - ARCH=aarch64
      - CARCH=odroid-c2
    - env:
      - ARCH=aarch64
      - CARCH=odroid-n2
    - env:
      - ARCH=aarch64
      - CARCH=oak
    - env:
      - ARCH=aarch64
      - CARCH=dragonboard410c
    - env:
      - ARCH=aarch64
      - CARCH=rpi-3
    - env:
      - ARCH=aarch64
      - CARCH=gru
